### ISSUE TITLE
Add "Moots" to Docs Working Group guide

### ISSUE THREAD

**Issue by ericsnekbytes** [jupyter/docs-team-compass#25]
As discussed in the weekly DWG meeting.

**Comment by willingc** [comment]
What or who is "Moots"?

**Comment by ericsnekbytes** [comment]
They're a specific type of event/meeting planned by the Docs Working Group (discussed in the last weekly meeting). The plan is for a member of the Docs Working Group to call for a moot, it will be announced (in the weekly meeting/elsewhere) for those who would like to help/collaborate on it, and for the event itself, we would invite and schedule experts on a particular topic/area of Jupyter to gather together with the DWG to record their knowledge/expertise and any undocumented information we can, with the goal of documenting that information somewhere for people to use (new docs or updates to existing ones etc).

**Comment by ericsnekbytes** [comment]
This is done, see the [Guide Book](https://github.com/jupyter/docs-team-compass/blob/main/guide_book.md) for notes about how to convene a moot :)
