### ISSUE TITLE
Rename this repository to `docs-team-compass`?

### ISSUE THREAD

**Issue by krassowski** [jupyter/docs-team-compass#5]
This would follow the pattern of other team-compasses:

![image](https://github.com/jupyter/docs/assets/5832902/2cca32ed-f201-4bce-bd50-68aa6884444e)

There is a team-compass template draft in https://github.com/jupyter/team-compass-template

Than we could split https://github.com/jupyter/jupyter into the metapackage and a new https://github.com/jupyter/docs laterif there are resources to do that?

**Comment by krassowski** [comment]
Maybe `documentation-team-compass` to make it easier to find?

**Comment by ericsnekbytes** [comment]
I would suggest docs-team-compass for brevity. I agree it would be preferable to split eventually, with `jupyter/docs` holding the meta docs if we decide to move them.

**Comment by ericsnekbytes** [comment]
BTW: Is it going to be a problem to rename this repo, then make a new repo with this one's current name? Does github do old-name-redirection or similar that would interfere with this?

**Comment by manics** [comment]
GitHub will redirect the old name, but will stop if you create a new repo with that name

**Comment by krassowski** [comment]
> but will stop if you create a new repo with that name

To clarify: it will stop redirecting from `org/old` to `org/new` once another `org/old` is created.

So there is not going to be a problem, I believe it is fine to rename :)

**Comment by ericsnekbytes** [comment]
Can you go ahead and make the change?

**Comment by krassowski** [comment]
Depends who is "you" in the comment above, but I do not have sufficient rights here, but I think you should have :)

**Comment by ericsnekbytes** [comment]
@krassowski I have write privileges, and you have maintainer privileges according to @willingc 's comment on the proposal thread. I don't have a settings tab for this repo so I don't think I can do it. If someone else can do it, let's go ahead :) For reference: https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository

**Comment by krassowski** [comment]
Maybe someone from @jupyter/executive-council could help with this.

**Comment by afshin** [comment]
Just to be sure, you want `jupyter/docs` to be renamed `jupyter/docs-team-compass`?

**Comment by krassowski** [comment]
Yes. There are no docs here right now, only future working group coordination; if we decide to move docs from `jupyter/jupyter` we can create a new repo and then name it `jupyter/docs`

**Comment by afshin** [comment]
Cool.

https://github.com/jupyter/docs-team-compass

**Comment by krassowski** [comment]
Thank you!
